; IRVibeOS system source.
; Rule: source that enters the system is LLVM IR only.

@banner = private unnamed_addr constant [38 x i8] c"IRVibeOS: LLVM IR only system surface\00"
@usage = private unnamed_addr constant [81 x i8] c"usage: lli src_ir/irvibeos.ll [boot|rewrite|exec|net|vibe]; no args enters shell\00"
@shell_intro = private unnamed_addr constant [82 x i8] c"IRVibeOS shell. Type help, apps, run, load, deps, vibe, net, rewrite, exec, exit.\00"
@prompt = private unnamed_addr constant [11 x i8] c"irvibeos> \00"
@module_prompt = private unnamed_addr constant [9 x i8] c"module> \00"
@intent_prompt = private unnamed_addr constant [9 x i8] c"intent> \00"
@scan_token = private unnamed_addr constant [5 x i8] c"%63s\00"

@boot_msg = private unnamed_addr constant [23 x i8] c"boot: Vibe core online\00"
@help_msg = private unnamed_addr constant [66 x i8] c"commands: help apps run load deps vibe net rewrite exec boot exit\00"
@apps_msg = private unnamed_addr constant [40 x i8] c"apps: dynamic IR modules under modules/\00"
@deps_msg = private unnamed_addr constant [37 x i8] c"deps: prints modules/<name>/deps.txt\00"
@run_msg = private unnamed_addr constant [49 x i8] c"run: executes modules/<name>/main.ll through lli\00"
@load_msg = private unnamed_addr constant [61 x i8] c"load: dependency-aware dynamic load, then executes module IR\00"
@rewrite_msg = private unnamed_addr constant [33 x i8] c"rewrite: wrote data/generated.ll\00"
@exec_msg = private unnamed_addr constant [39 x i8] c"exec: running generated IR through lli\00"
@net_msg = private unnamed_addr constant [53 x i8] c"net: fetching https://example.com into data/net.last\00"
@vibe_msg = private unnamed_addr constant [46 x i8] c"vibe: choose module name and one intent token\00"
@vibe_done_fmt = private unnamed_addr constant [45 x i8] c"vibe: wrote modules/%s/main.ll and deps.txt\0A\00"
@unknown_msg = private unnamed_addr constant [16 x i8] c"unknown command\00"

@cmd_exit = private unnamed_addr constant [5 x i8] c"exit\00"
@cmd_help = private unnamed_addr constant [5 x i8] c"help\00"
@cmd_apps = private unnamed_addr constant [5 x i8] c"apps\00"
@cmd_run = private unnamed_addr constant [4 x i8] c"run\00"
@cmd_load = private unnamed_addr constant [5 x i8] c"load\00"
@cmd_deps = private unnamed_addr constant [5 x i8] c"deps\00"
@cmd_boot = private unnamed_addr constant [5 x i8] c"boot\00"
@cmd_rewrite = private unnamed_addr constant [8 x i8] c"rewrite\00"
@cmd_exec = private unnamed_addr constant [5 x i8] c"exec\00"
@cmd_net = private unnamed_addr constant [4 x i8] c"net\00"
@cmd_vibe = private unnamed_addr constant [5 x i8] c"vibe\00"

@apps_cmd = private unnamed_addr constant [21 x i8] c"dir /b modules 2>nul\00"
@deps_fmt = private unnamed_addr constant [25 x i8] c"type modules\5C%s\5Cdeps.txt\00"
@run_fmt = private unnamed_addr constant [23 x i8] c"lli modules\5C%s\5Cmain.ll\00"
@load_fmt = private unnamed_addr constant [77 x i8] c"echo Loading module %s && type modules\5C%s\5Cdeps.txt && lli modules\5C%s\5Cmain.ll\00"
@mkdir_modules_cmd = private unnamed_addr constant [20 x i8] c"mkdir modules 2>nul\00"
@mkdir_module_fmt = private unnamed_addr constant [23 x i8] c"mkdir modules\5C%s 2>nul\00"
@module_main_path_fmt = private unnamed_addr constant [19 x i8] c"modules\5C%s\5Cmain.ll\00"
@module_deps_path_fmt = private unnamed_addr constant [20 x i8] c"modules\5C%s\5Cdeps.txt\00"
@mkdir_data_cmd = private unnamed_addr constant [17 x i8] c"mkdir data 2>nul\00"
@run_generated_cmd = private unnamed_addr constant [22 x i8] c"lli data/generated.ll\00"
@curl_cmd = private unnamed_addr constant [45 x i8] c"curl -L https://example.com -o data/net.last\00"
@write_mode = private unnamed_addr constant [3 x i8] c"wb\00"
@generated_path = private unnamed_addr constant [18 x i8] c"data/generated.ll\00"
@generated_ir = private unnamed_addr constant [207 x i8] c"; generated by IRVibeOS rewrite\0A@msg = private unnamed_addr constant [29 x i8] c\22generated IR module executed\5C00\22\0Adeclare i32 @puts(ptr)\0Adefine i32 @main() {\0Aentry:\0A  call i32 @puts(ptr @msg)\0A  ret i32 0\0A}\0A\00"
@vibe_module_fmt = private unnamed_addr constant [225 x i8] c"; generated by IRVibeOS vibe\0A; intent-token: %s\0A@msg = private unnamed_addr constant [31 x i8] c\22vibe generated module executed\5C00\22\0Adeclare i32 @puts(ptr)\0Adefine i32 @main() {\0Aentry:\0A  call i32 @puts(ptr @msg)\0A  ret i32 0\0A}\0A\00"
@vibe_deps_fmt = private unnamed_addr constant [49 x i8] c"irvibeos.core >= 0.1\0Alibc.puts\0Aintent-token: %s\0A\00"

declare i32 @puts(ptr)
declare i32 @printf(ptr, ...)
declare i32 @scanf(ptr, ...)
declare i32 @sprintf(ptr, ptr, ...)
declare i32 @fprintf(ptr, ptr, ...)
declare i32 @strcmp(ptr, ptr)
declare i32 @system(ptr)
declare i32 @fflush(ptr)
declare ptr @fopen(ptr, ptr)
declare i32 @fputs(ptr, ptr)
declare i32 @fclose(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %command_buf = alloca [64 x i8]
  %module_buf = alloca [64 x i8]
  %intent_buf = alloca [64 x i8]
  %system_buf = alloca [256 x i8]
  %command = getelementptr [64 x i8], ptr %command_buf, i64 0, i64 0
  %module = getelementptr [64 x i8], ptr %module_buf, i64 0, i64 0
  %intent = getelementptr [64 x i8], ptr %intent_buf, i64 0, i64 0
  %system_command = getelementptr [256 x i8], ptr %system_buf, i64 0, i64 0
  call i32 @puts(ptr @banner)
  %has_command = icmp sgt i32 %argc, 1
  br i1 %has_command, label %dispatch_argv, label %shell_start

dispatch_argv:
  %argv1_slot = getelementptr ptr, ptr %argv, i64 1
  %argv_command = load ptr, ptr %argv1_slot
  call void @dispatch(ptr %argv_command, ptr %module, ptr %intent, ptr %system_command, i1 false)
  ret i32 0

shell_start:
  call i32 @puts(ptr @shell_intro)
  br label %shell_loop

shell_loop:
  call i32 (ptr, ...) @printf(ptr @prompt)
  call i32 @fflush(ptr null)
  %read = call i32 (ptr, ...) @scanf(ptr @scan_token, ptr %command)
  %read_ok = icmp eq i32 %read, 1
  br i1 %read_ok, label %shell_dispatch, label %shell_exit

shell_dispatch:
  %exit_cmp = call i32 @strcmp(ptr %command, ptr @cmd_exit)
  %is_exit = icmp eq i32 %exit_cmp, 0
  br i1 %is_exit, label %shell_exit, label %shell_continue

shell_continue:
  call void @dispatch(ptr %command, ptr %module, ptr %intent, ptr %system_command, i1 true)
  br label %shell_loop

shell_exit:
  ret i32 0
}

define void @dispatch(ptr %command, ptr %module, ptr %intent, ptr %system_command, i1 %interactive) {
entry:
  %help_cmp = call i32 @strcmp(ptr %command, ptr @cmd_help)
  %is_help = icmp eq i32 %help_cmp, 0
  br i1 %is_help, label %help_block, label %check_apps

check_apps:
  %apps_cmp = call i32 @strcmp(ptr %command, ptr @cmd_apps)
  %is_apps = icmp eq i32 %apps_cmp, 0
  br i1 %is_apps, label %apps_block, label %check_run

check_run:
  %run_cmp = call i32 @strcmp(ptr %command, ptr @cmd_run)
  %is_run = icmp eq i32 %run_cmp, 0
  br i1 %is_run, label %run_block, label %check_load

check_load:
  %load_cmp = call i32 @strcmp(ptr %command, ptr @cmd_load)
  %is_load = icmp eq i32 %load_cmp, 0
  br i1 %is_load, label %load_block, label %check_deps

check_deps:
  %deps_cmp = call i32 @strcmp(ptr %command, ptr @cmd_deps)
  %is_deps = icmp eq i32 %deps_cmp, 0
  br i1 %is_deps, label %deps_block, label %check_boot

check_boot:
  %boot_cmp = call i32 @strcmp(ptr %command, ptr @cmd_boot)
  %is_boot = icmp eq i32 %boot_cmp, 0
  br i1 %is_boot, label %boot_block, label %check_rewrite

check_rewrite:
  %rewrite_cmp = call i32 @strcmp(ptr %command, ptr @cmd_rewrite)
  %is_rewrite = icmp eq i32 %rewrite_cmp, 0
  br i1 %is_rewrite, label %rewrite_block, label %check_exec

check_exec:
  %exec_cmp = call i32 @strcmp(ptr %command, ptr @cmd_exec)
  %is_exec = icmp eq i32 %exec_cmp, 0
  br i1 %is_exec, label %exec_block, label %check_net

check_net:
  %net_cmp = call i32 @strcmp(ptr %command, ptr @cmd_net)
  %is_net = icmp eq i32 %net_cmp, 0
  br i1 %is_net, label %net_block, label %check_vibe

check_vibe:
  %vibe_cmp = call i32 @strcmp(ptr %command, ptr @cmd_vibe)
  %is_vibe = icmp eq i32 %vibe_cmp, 0
  br i1 %is_vibe, label %vibe_block, label %unknown_block

help_block:
  call i32 @puts(ptr @help_msg)
  call i32 @puts(ptr @deps_msg)
  call i32 @puts(ptr @run_msg)
  call i32 @puts(ptr @load_msg)
  ret void

apps_block:
  call i32 @puts(ptr @apps_msg)
  call i32 @fflush(ptr null)
  call i32 @system(ptr @apps_cmd)
  ret void

run_block:
  call void @read_module(ptr %module)
  call i32 (ptr, ptr, ...) @sprintf(ptr %system_command, ptr @run_fmt, ptr %module)
  call i32 @fflush(ptr null)
  call i32 @system(ptr %system_command)
  ret void

load_block:
  call void @read_module(ptr %module)
  call i32 (ptr, ptr, ...) @sprintf(ptr %system_command, ptr @load_fmt, ptr %module, ptr %module, ptr %module)
  call i32 @fflush(ptr null)
  call i32 @system(ptr %system_command)
  ret void

deps_block:
  call void @read_module(ptr %module)
  call i32 (ptr, ptr, ...) @sprintf(ptr %system_command, ptr @deps_fmt, ptr %module)
  call i32 @fflush(ptr null)
  call i32 @system(ptr %system_command)
  ret void

boot_block:
  call i32 @puts(ptr @boot_msg)
  ret void

rewrite_block:
  call void @rewrite_action()
  ret void

exec_block:
  call i32 @puts(ptr @exec_msg)
  call i32 @fflush(ptr null)
  call i32 @system(ptr @run_generated_cmd)
  ret void

net_block:
  call i32 @puts(ptr @net_msg)
  call i32 @fflush(ptr null)
  call i32 @system(ptr @mkdir_data_cmd)
  call i32 @system(ptr @curl_cmd)
  ret void

vibe_block:
  call void @vibe_action(ptr %module, ptr %intent, ptr %system_command)
  ret void

unknown_block:
  call i32 @puts(ptr @unknown_msg)
  ret void
}

define void @read_module(ptr %module) {
entry:
  call i32 (ptr, ...) @printf(ptr @module_prompt)
  call i32 @fflush(ptr null)
  call i32 (ptr, ...) @scanf(ptr @scan_token, ptr %module)
  ret void
}

define void @read_intent(ptr %intent) {
entry:
  call i32 (ptr, ...) @printf(ptr @intent_prompt)
  call i32 @fflush(ptr null)
  call i32 (ptr, ...) @scanf(ptr @scan_token, ptr %intent)
  ret void
}

define void @vibe_action(ptr %module, ptr %intent, ptr %system_command) {
entry:
  call i32 @puts(ptr @vibe_msg)
  call void @read_module(ptr %module)
  call void @read_intent(ptr %intent)
  call i32 @system(ptr @mkdir_modules_cmd)
  call i32 (ptr, ptr, ...) @sprintf(ptr %system_command, ptr @mkdir_module_fmt, ptr %module)
  call i32 @system(ptr %system_command)
  call i32 (ptr, ptr, ...) @sprintf(ptr %system_command, ptr @module_main_path_fmt, ptr %module)
  %main_file = call ptr @fopen(ptr %system_command, ptr @write_mode)
  %main_ok = icmp ne ptr %main_file, null
  br i1 %main_ok, label %write_main, label %write_deps_path

write_main:
  call i32 (ptr, ptr, ...) @fprintf(ptr %main_file, ptr @vibe_module_fmt, ptr %intent)
  call i32 @fclose(ptr %main_file)
  br label %write_deps_path

write_deps_path:
  call i32 (ptr, ptr, ...) @sprintf(ptr %system_command, ptr @module_deps_path_fmt, ptr %module)
  %deps_file = call ptr @fopen(ptr %system_command, ptr @write_mode)
  %deps_ok = icmp ne ptr %deps_file, null
  br i1 %deps_ok, label %write_deps, label %vibe_done

write_deps:
  call i32 (ptr, ptr, ...) @fprintf(ptr %deps_file, ptr @vibe_deps_fmt, ptr %intent)
  call i32 @fclose(ptr %deps_file)
  br label %vibe_done

vibe_done:
  call i32 (ptr, ...) @printf(ptr @vibe_done_fmt, ptr %module)
  ret void
}

define void @rewrite_action() {
entry:
  call i32 @system(ptr @mkdir_data_cmd)
  %file = call ptr @fopen(ptr @generated_path, ptr @write_mode)
  %file_ok = icmp ne ptr %file, null
  br i1 %file_ok, label %write_generated, label %rewrite_done

write_generated:
  call i32 @fputs(ptr @generated_ir, ptr %file)
  call i32 @fclose(ptr %file)
  br label %rewrite_done

rewrite_done:
  call i32 @puts(ptr @rewrite_msg)
  ret void
}
