"""Hosted IRVibeOS 1.0 vibe tool.

This tool implements the first usable loop:
intent -> LLVM IR -> llvm-as verification -> modules/<name>/main.ll -> optional lli run.

Host tooling is allowed to be Python. System/device source remains LLVM IR.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path


MODULE_RE = re.compile(r"^[A-Za-z0-9_-]+$")


def fail(message: str, code: int = 1) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(code)


def run_cmd(args: list[str], *, input_text: str | None = None, timeout: int = 60) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        args,
        input=input_text,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=timeout,
    )


def require_tool(name: str) -> None:
    try:
        result = run_cmd([name, "--version"], timeout=10)
    except FileNotFoundError:
        fail(f"{name} was not found in PATH")
    if result.returncode != 0:
        fail(f"{name} exists but failed to run: {result.stderr.strip()}")


def llvm_c_string(text: str) -> tuple[int, str]:
    data = text.encode("utf-8") + b"\n\0"
    out = []
    for byte in data:
        if 32 <= byte <= 126 and byte not in (34, 92):
            out.append(chr(byte))
        else:
            out.append(f"\\{byte:02X}")
    return len(data), "".join(out)


def template_ir(intent: str) -> str:
    message = f"IRVibeOS hosted vibe: {intent}"
    length, escaped = llvm_c_string(message)
    return f"""; generated by IRVibeOS hosted_vibe.py
; provider: template
; intent: {intent}

@msg = private unnamed_addr constant [{length} x i8] c"{escaped}"

declare i32 @puts(ptr)

define i32 @main() {{
entry:
  call i32 @puts(ptr @msg)
  ret i32 0
}}
"""


def strip_markdown_fence(text: str) -> str:
    stripped = text.strip()
    if not stripped.startswith("```"):
        return stripped

    lines = stripped.splitlines()
    if lines and lines[0].startswith("```"):
        lines = lines[1:]
    if lines and lines[-1].strip().startswith("```"):
        lines = lines[:-1]
    return "\n".join(lines).strip() + "\n"


def load_context(repo_root: Path) -> str:
    paths = [
        repo_root / "README.md",
        repo_root / "knowledge" / "README.md",
        repo_root / "knowledge" / "examples" / "hello.ll",
        repo_root / "modules" / "hello" / "main.ll",
    ]
    chunks: list[str] = []
    for path in paths:
        if path.exists():
            chunks.append(f"--- {path.relative_to(repo_root)} ---\n{path.read_text(encoding='utf-8', errors='replace')[:3000]}")
    return "\n\n".join(chunks)


def build_system_prompt(context: str) -> str:
    return f"""You generate LLVM IR modules for IRVibeOS hosted mode.

Return only raw LLVM IR. Do not use markdown fences.

Rules:
- Use opaque pointers: ptr, not i8*.
- Provide define i32 @main().
- Prefer simple libc calls such as puts or printf.
- Declare every external function you call.
- Keep the module small and deterministic.
- Do not emit shell commands, files, networking, or platform-specific APIs unless the user explicitly asks.
- The output must pass llvm-as.

Local repository context:
{context}
"""


def call_openai_compatible(api_base: str, api_key: str, model: str, system_prompt: str, intent: str) -> str:
    try:
        import requests
    except ImportError as exc:
        raise RuntimeError("requests is required for AI providers. Install with: pip install requests") from exc

    url = api_base.rstrip("/") + "/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    body = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": intent},
        ],
        "temperature": 0.2,
        "max_tokens": 4096,
    }
    response = requests.post(url, headers=headers, json=body, timeout=90)
    response.raise_for_status()
    data = response.json()
    return data["choices"][0]["message"]["content"]


def call_claude(api_key: str, model: str, system_prompt: str, intent: str) -> str:
    try:
        import requests
    except ImportError as exc:
        raise RuntimeError("requests is required for AI providers. Install with: pip install requests") from exc

    headers = {
        "x-api-key": api_key,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
    }
    body = {
        "model": model,
        "max_tokens": 4096,
        "system": system_prompt,
        "messages": [{"role": "user", "content": intent}],
    }
    response = requests.post("https://api.anthropic.com/v1/messages", headers=headers, json=body, timeout=90)
    response.raise_for_status()
    data = response.json()
    return data["content"][0]["text"]


def generate_ir(args: argparse.Namespace, repo_root: Path) -> str:
    if args.provider == "template":
        return template_ir(args.intent)

    context = load_context(repo_root)
    system_prompt = build_system_prompt(context)

    if args.provider in ("openai", "openai-compatible"):
        api_key = args.api_key or os.environ.get("OPENAI_API_KEY") or os.environ.get("IRVIBEOS_API_KEY")
        if not api_key:
            fail("missing API key; pass --api-key or set OPENAI_API_KEY / IRVIBEOS_API_KEY")
        api_base = args.api_base or os.environ.get("IRVIBEOS_API_BASE")
        if not api_base:
            api_base = "https://api.openai.com/v1" if args.provider == "openai" else "http://localhost:11434/v1"
        model = args.model or os.environ.get("IRVIBEOS_MODEL")
        if not model:
            fail("missing model; pass --model or set IRVIBEOS_MODEL")
        return strip_markdown_fence(call_openai_compatible(api_base, api_key, model, system_prompt, args.intent))

    if args.provider == "claude":
        api_key = args.api_key or os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("IRVIBEOS_API_KEY")
        if not api_key:
            fail("missing API key; pass --api-key or set ANTHROPIC_API_KEY / IRVIBEOS_API_KEY")
        model = args.model or os.environ.get("IRVIBEOS_MODEL")
        if not model:
            fail("missing model; pass --model or set IRVIBEOS_MODEL")
        return strip_markdown_fence(call_claude(api_key, model, system_prompt, args.intent))

    fail(f"unsupported provider: {args.provider}")
    raise AssertionError("unreachable")


def verify_ir(ir_text: str) -> None:
    require_tool("llvm-as")
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", suffix=".ll", delete=False) as temp:
        temp.write(ir_text)
        temp_path = Path(temp.name)
    bc_path = temp_path.with_suffix(".bc")
    try:
        result = run_cmd(["llvm-as", str(temp_path), "-o", str(bc_path)], timeout=30)
        if result.returncode != 0:
            fail("generated IR failed llvm-as verification:\n" + result.stderr.strip())
    finally:
        temp_path.unlink(missing_ok=True)
        bc_path.unlink(missing_ok=True)


def save_module(modules_dir: Path, name: str, ir_text: str, intent: str, provider: str, force: bool) -> Path:
    if not MODULE_RE.match(name):
        fail("module name must contain only letters, digits, underscore, or hyphen")

    module_dir = modules_dir / name
    main_path = module_dir / "main.ll"
    deps_path = module_dir / "deps.txt"

    if main_path.exists() and not force:
        fail(f"{main_path} already exists; pass --force to overwrite")

    module_dir.mkdir(parents=True, exist_ok=True)
    main_path.write_text(ir_text, encoding="utf-8")
    deps_path.write_text(
        f"irvibeos.core >= 1.0\nprovider: {provider}\nintent: {intent}\n",
        encoding="utf-8",
    )
    return main_path


def run_module(main_path: Path) -> int:
    require_tool("lli")
    result = run_cmd(["lli", str(main_path)], timeout=30)
    if result.stdout:
        print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, file=sys.stderr, end="")
    return result.returncode


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a hosted IRVibeOS module from an intent.")
    parser.add_argument("--name", required=True, help="module name under modules/")
    parser.add_argument("--intent", required=True, help="intent to implement")
    parser.add_argument(
        "--provider",
        choices=["template", "openai", "openai-compatible", "claude"],
        default="template",
        help="generation provider; template is offline and deterministic",
    )
    parser.add_argument("--api-key", help="API key for AI providers")
    parser.add_argument("--api-base", help="OpenAI-compatible API base URL")
    parser.add_argument("--model", help="AI model name")
    parser.add_argument("--modules-dir", default="modules", help="module registry directory")
    parser.add_argument("--force", action="store_true", help="overwrite an existing module")
    parser.add_argument("--run", action="store_true", help="run the module with lli after saving")
    parser.add_argument("--print-ir", action="store_true", help="print generated IR")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    repo_root = Path.cwd()
    modules_dir = (repo_root / args.modules_dir).resolve()

    ir_text = strip_markdown_fence(generate_ir(args, repo_root))
    verify_ir(ir_text)

    if args.print_ir:
        print(ir_text)

    main_path = save_module(modules_dir, args.name, ir_text, args.intent, args.provider, args.force)
    print(f"Saved module: {main_path}")

    if args.run:
        return run_module(main_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
