"""Vibe providers — AI backends for IR generation.

Each provider implements generate() and repair() methods that return raw text.
The protocol layer handles verification and retry logic.
"""

from __future__ import annotations

import os
from abc import ABC, abstractmethod

from .ir_utils import llvm_c_string
from .prompts import SYSTEM_PROMPT_IR, build_generation_messages, build_repair_messages


class VibeProvider(ABC):
    """Abstract base for IR generation providers."""

    @abstractmethod
    def generate(self, intent: str) -> str:
        """Generate LLVM IR from an intent string. Returns raw text."""
        ...

    @abstractmethod
    def repair(self, original_ir: str, error: str) -> str:
        """Attempt to fix IR given the llvm-as error. Returns raw text."""
        ...


class TemplateProvider(VibeProvider):
    """Offline deterministic provider — generates a puts-based module."""

    def generate(self, intent: str) -> str:
        message = f"IRVibeOS hosted vibe: {intent}"
        length, escaped = llvm_c_string(message)
        return f"""; generated by IRVibeOS vibe (template)
; intent: {intent}

@msg = private unnamed_addr constant [{length} x i8] c"{escaped}"

declare i32 @puts(ptr)

define i32 @main() {{
entry:
  call i32 @puts(ptr @msg)
  ret i32 0
}}
"""

    def repair(self, original_ir: str, error: str) -> str:
        # Template output is deterministic and always valid — repair is a no-op.
        return original_ir


# ---------------------------------------------------------------------------
# AI-backed providers (require `requests`)
# ---------------------------------------------------------------------------

class _AIProviderBase(VibeProvider):
    """Shared logic for AI-backed providers."""

    def __init__(self, api_key: str, model: str, **kwargs):
        self.api_key = api_key
        self.model = model

    @abstractmethod
    def _call(self, system: str, messages: list[dict]) -> str:
        """Send a chat completion request and return the content."""
        ...

    def generate(self, intent: str) -> str:
        messages = build_generation_messages(intent, include_examples=True)
        return self._call(SYSTEM_PROMPT_IR, messages)

    def repair(self, original_ir: str, error: str) -> str:
        messages = build_repair_messages(original_ir, error)
        return self._call(SYSTEM_PROMPT_IR, messages)


class OpenAIProvider(_AIProviderBase):
    """OpenAI and OpenAI-compatible API provider."""

    def __init__(self, api_key: str, model: str, api_base: str | None = None, **kwargs):
        super().__init__(api_key, model)
        self.api_base = (api_base or "https://api.openai.com/v1").rstrip("/")

    def _call(self, system: str, messages: list[dict]) -> str:
        import requests

        url = f"{self.api_base}/chat/completions"
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        body = {
            "model": self.model,
            "messages": [{"role": "system", "content": system}] + messages,
            "temperature": 0.2,
            "max_tokens": 4096,
        }
        resp = requests.post(url, headers=headers, json=body, timeout=90)
        resp.raise_for_status()
        return resp.json()["choices"][0]["message"]["content"]


class ClaudeProvider(_AIProviderBase):
    """Anthropic Claude API provider."""

    def __init__(self, api_key: str, model: str, **kwargs):
        super().__init__(api_key, model)

    def _call(self, system: str, messages: list[dict]) -> str:
        import requests

        headers = {
            "x-api-key": self.api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        }
        body = {
            "model": self.model,
            "max_tokens": 4096,
            "system": system,
            "messages": messages,
        }
        resp = requests.post(
            "https://api.anthropic.com/v1/messages",
            headers=headers,
            json=body,
            timeout=90,
        )
        resp.raise_for_status()
        return resp.json()["content"][0]["text"]


def create_provider(
    provider_name: str,
    api_key: str | None = None,
    model: str | None = None,
    api_base: str | None = None,
) -> VibeProvider:
    """Factory: create a provider by name.

    Resolves API keys from environment if not passed directly.
    """
    if provider_name == "template":
        return TemplateProvider()

    if provider_name in ("openai", "openai-compatible"):
        key = api_key or os.environ.get("OPENAI_API_KEY") or os.environ.get("IRVIBEOS_API_KEY")
        if not key:
            raise ValueError("API key required: pass --api-key or set OPENAI_API_KEY / IRVIBEOS_API_KEY")
        mdl = model or os.environ.get("IRVIBEOS_MODEL")
        if not mdl:
            raise ValueError("Model required: pass --model or set IRVIBEOS_MODEL")
        base = api_base or os.environ.get("IRVIBEOS_API_BASE")
        if not base:
            base = "https://api.openai.com/v1" if provider_name == "openai" else "http://localhost:11434/v1"
        return OpenAIProvider(api_key=key, model=mdl, api_base=base)

    if provider_name == "claude":
        key = api_key or os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("IRVIBEOS_API_KEY")
        if not key:
            raise ValueError("API key required: pass --api-key or set ANTHROPIC_API_KEY / IRVIBEOS_API_KEY")
        mdl = model or os.environ.get("IRVIBEOS_MODEL")
        if not mdl:
            raise ValueError("Model required: pass --model or set IRVIBEOS_MODEL")
        return ClaudeProvider(api_key=key, model=mdl)

    raise ValueError(f"Unknown provider: {provider_name}")
